apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  namespace: devopschallenge
  labels:
      app: node-app
      type: front-end
spec:
 containers:
  - name: test-container
    image: bakra43/test
    

---
apiVersion: v1
kind: Namespace
metadata:
    name: devopschallenge

---
apiVersion: v1
kind: ResourceQuota
metadata:
    name: compute-quota
    namespace: devopschallenge

spec:
  hard:
    pods: "12"
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "16"
    limits.memory: 12Gi