apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-rs
  labels:
      app: node-app
      type: front-end
spec:
  template:
    metadata:
  name: node-pod
  labels:
      app: node-app
      type: front-end
  spec:
  containers:
    - name: test-container
      image: bakra43/test

  replicas: 3
  selector:
    matchLabels:
      type: front-end
