apiVersion: v1
kind: Service
metadata:
  name: node-service

spec:
    type: NodePort
    ports:
      - targetPort: 80
        port: 80
        nodePort: 30008
    selector:
        app: node-app
        type: front-end

---
apiVersion: v1
kind: Service
metadata:
  name: node-bck

spec:
    type: ClusterIP
    ports:
      - targetPort: 80
        port: 80
    selector:
        app: node-app
        type: back-end

---
apiVersion: v1
kind: Service
metadata:
  name: node-service

spec:
    type: LoadBalancer
    ports:
      - targetPort: 80
        port: 80
        nodePort: 30008
    selector:
        app: node-app
        type: front-end