apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw-ingress
  #namespace: devopschallenge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nikolabakracevski.me
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: "true"
    cert-manager.io/issuer: letsencrypt-production
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - secretName: webski-ssl
      hosts:
        - nikolabakracevski.me
  rules:
  - host: nikolabakracevski.me
    http:
      paths:
      - pathType: Prefix
        path: "/"  
        backend:
          service:
            name: example-service
            port:
              number: 3000