apiVersion: v1
kind: Secret
metadata:
  name: webski-ssl
type: kubernetes.io/tls
stringData:
  tls.key: ""
  tls.crt: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: client-secret
stringData:
  api-token: "your cloudlflare secret"